import type { CatppuccinVariant, ThemeFamilyOption } from "./types";

export const THEME_FAMILIES: ThemeFamilyOption[] = [
  {
    id: "default",
    label: "Default",
    description: "Clean, neutral, modern",
    previewBgDark: "#1e1e20",
    previewBgLight: "#f8f8f9",
    previewCardDark: "rgba(32, 32, 35, 0.82)",
    previewCardLight: "rgba(255, 255, 255, 0.85)",
    previewTextDark: "#e8e8ea",
    previewTextLight: "#1c1c1e",
    previewAccentDark: "#d8d8da",
    previewAccentLight: "#2a2a2e",
    hasLightVariant: true,
  },
  {
    id: "catppuccin",
    label: "Catppuccin",
    description: "Soothing pastel theme",
    previewBgDark: "#1e1e2e",
    previewBgLight: "#eff1f5",
    previewCardDark: "rgba(49, 50, 68, 0.72)",
    previewCardLight: "rgba(255, 255, 254, 0.72)",
    previewTextDark: "#cdd6f4",
    previewTextLight: "#4c4f69",
    previewAccentDark: "#89b4fa",
    previewAccentLight: "#1e66f5",
    hasLightVariant: true,
  },
  {
    id: "nord",
    label: "Nord",
    description: "Arctic, bluish palette",
    previewBgDark: "#2e3440",
    previewBgLight: "#e8eef0",
    previewCardDark: "rgba(59, 66, 82, 0.72)",
    previewCardLight: "rgba(255, 255, 255, 0.72)",
    previewTextDark: "#eceff4",
    previewTextLight: "#2e3440",
    previewAccentDark: "#88c0d0",
    previewAccentLight: "#5e81ac",
    hasLightVariant: true,
  },
  {
    id: "tokyo-night",
    label: "Tokyo Night",
    description: "Tokyo neon lights",
    previewBgDark: "#1a1b26",
    previewBgLight: "#e1e2eb",
    previewCardDark: "rgba(36, 40, 59, 0.72)",
    previewCardLight: "rgba(255, 255, 255, 0.72)",
    previewTextDark: "#c0caf5",
    previewTextLight: "#343b59",
    previewAccentDark: "#7aa2f7",
    previewAccentLight: "#3484e4",
    hasLightVariant: true,
  },
  {
    id: "gruvbox",
    label: "Gruvbox",
    description: "Retro warm colors",
    previewBgDark: "#282828",
    previewBgLight: "#fbf1c7",
    previewCardDark: "rgba(60, 56, 54, 0.72)",
    previewCardLight: "rgba(255, 251, 241, 0.72)",
    previewTextDark: "#ebdbb2",
    previewTextLight: "#282828",
    previewAccentDark: "#fe8019",
    previewAccentLight: "#d79921",
    hasLightVariant: true,
  },
  {
    id: "one-dark",
    label: "One Dark",
    description: "Atom's iconic theme",
    previewBgDark: "#282c34",
    previewBgLight: "#fafafa",
    previewCardDark: "rgba(59, 64, 72, 0.72)",
    previewCardLight: "rgba(255, 255, 255, 0.72)",
    previewTextDark: "#abb2bf",
    previewTextLight: "#383a42",
    previewAccentDark: "#61afef",
    previewAccentLight: "#528bff",
    hasLightVariant: true,
  },
  {
    id: "dracula",
    label: "Dracula",
    description: "Dark purple-tinted",
    previewBgDark: "#282a36",
    previewBgLight: "#f5f5f4",
    previewCardDark: "rgba(68, 71, 90, 0.72)",
    previewCardLight: "rgba(255, 255, 254, 0.72)",
    previewTextDark: "#f8f8f2",
    previewTextLight: "#1c1c1a",
    previewAccentDark: "#bd93f9",
    previewAccentLight: "#bd93f9",
    hasLightVariant: false,
  },
];

export const CATPPUCCIN_VARIANTS: { id: CatppuccinVariant; label: string; isDark: boolean }[] = [
  { id: "mocha", label: "Mocha", isDark: true },
  { id: "macchiato", label: "Macchiato", isDark: true },
  { id: "frappe", label: "Frappé", isDark: true },
  { id: "latte", label: "Latte", isDark: false },
];

