providers = ["node"]

[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun --filter @khadim/web build"]

[start]
cmd = "bun --filter @khadim/web start"
